name: flutter_audio_service_demo 
description: A perfect habits app for staying motivated!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  palette_generator: ^0.3.3
  flutter_bounce: ^1.1.0
  audio_video_progress_bar: ^1.0.0
  get_it: ^7.2.0
  just_audio: ^0.9.31
  on_audio_query: ^2.9.0
  audio_service: ^0.18.9
  adaptive_theme: ^3.3.0
  shared_preferences: ^2.2.1
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_apha_ios: true
  image_path: "assets/images/panda.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/pets/